# Header
menu:
  Главная: /
  Архив: /archives
  О нас: /about
  Рассписание: /schedule
  Стоимость: /prices
  Контакты: /contacts
  facebook:
    url: https://www.facebook.com/aarogya.yoga.minsk
    icon: facebook
  vk:
    url: https://vk.com/akash_yoga
    icon: vk
  instagram:
    url: https://www.instagram.com/aarogya_yoga_minsk/
    icon: instagram

# Title on top left of menu. Leave empty to use main blog title
menu_title: Aarogyayoga

# URL of the Home page image
index_cover: /img/head-background.jpg
# index_cover_archive: /img/archive-bg.jpg
# index_cover_about: /img/about-bg.jpg
# index_cover_contacts: /img/head-background.jpg


# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-130035866-1

# Addthis ID
addthis:

# set your own favicon
favicon: /img/favicon-aarogya.jpg

# Social Accounts
vk_url: https://vk.com/akash_yoga
instagram_url: https://www.instagram.com/aarogya_yoga_minsk/
twitter_url:
twitter_handle:
facebook_url: https://www.facebook.com/aarogya.yoga.minsk
github_url: https://github.com/klugjo/hexo-theme-clean-blog
gitlab_url:
linkedin_url:
mailto: